broadinstitute/viral-core

docker/install-gatk.sh

DSP has updated the GATK website, breaking links to older versions. Tarballs for the older versions are preserved on GS with public links: https://console.cloud.google.com/storage/browser/gatk-software/package-archive/gatk
This commit updates the source url for the gatk 3.8 tarball to point to the new home on GS.

update source url for obtaining gatk 3.8

---

read_utils.py

The old mvicuna post-processing code expects read IDs to have a `/1` mate suffix, and only includes those that do, which single-end reads do not have (nor interleaved fastqs, but that's a separate issue and we're generating the fastqs for this internal function ourselves so interleaving should not be an issue). So no single-end IDs were preserved. This PR ensures single-end read IDs make it through this post-processing.
Closes https://github.com/broadinstitute/viral-classify/issues/5

do not discard read IDs for single-end reads after running mvicuna

---

reports.py
tools/fastqc.py

allow reports.pt::fastqc to output data zip archives, as these files are used by downstream tools such as MultiQC

allow reports.pt::fastqc to output data zip archives

---

docker/calc_mem.py

allow calc_mem.py script to return mem per cpu if `--per-cpu` flag is set

allow calc_mem.py script to return mem per cpu

---

illumina.py
util/file.py

`illumina.count_and_sort_barcodes()` was running out of memory on large sequencer runs (i.e. NovaSeq data). These changes move barcode counting storage from an in-mem dict (which increases in size by powers of 2 with each resize step where resizing occurs when the key use reaches 2/3 capacity, at least in cPython) to a disk-backed temporary SQLite database. Tile counting is sharded over separate processes, where each writes barcode counts to its own temporary SQLite database. As threads finish, the database-held counts are merged in SQLite-space which is pretty fast. Then we continue as before writing out the barcodes and the index names we've guessed (which is now the slowest part of this process after Picard `ExtractIlluminaBarcodesTool`). Attention has been spent to batch reads and …

optimize barcode counting w/ switch to SQLite

---

illumina.py

This adds a new --append_run_id boolean option to illumina_demux that causes output filenames to be appended with `.<flowcell_id>.<lane_num>`. It is off by default.

add --append_run_id to illumina_demux

---

read_utils.py
util/misc.py

fix to parsing of passed JVMmemory value so it is interpreted correctly before dividing among worker threads; add util.misc.convert_size_str() to read and convert JVM-like mem spec strings

JVMmemory parse fix for downsample_bams

---

tools/gatk.py
tools/samtools.py

this was causing errors in read_utils.py gatk_ug (which doesn't have test coverage currently in viral-core, just in viral-assemble)

bugfix version fetching for gatk and samtools

---

tools/minimap2.py

When writing empty bam files, make sure the header says `SO:coordinate` instead of `SO:unsorted`, otherwise some downstream tools (such as Picard MarkDuplicates) will [complain](https://job-manager.dsde-prod.broadinstitute.org/jobs/108e6fb1-94ff-420c-94f2-2f79416c8d89) about it being unsorted (even though there are no reads).

minimap2 empty output bam fix

---

illumina.py

pass through `append_run_id` to `get_SampleSheet()` in the case where a sample sheet csv is not explicitly provided when calling `illumina.py illumina_demux`

bugfix: pass through append_run_id arg

---

tools/minimap2.py

fix minimap.align_one_rg when given an empty input bam with one read group (this previously worked fine when some read groups were empty in a multi RG bam, but didn't work with a single-RG empty input bam).

minimap2 empty input bugfix

---

read_utils.py
tools/samtools.py

* add `samtools.filter_to_mapped_reads()` function to remove duplicates, and reads that are not properly paired, with options to allow unmapped reads and singletons, and to filter based on mapping score
* in `read_utils.align_and_fix()`, replace `samtools -F 1028` with filters on input and output via samtools.filter_to_mapped_reads(), such that marked pcr duplicates and mapped singletons are removed on the input side, and on the output side marked duplicates are removed as well as any reads not properly paired, except for single-end reads, which are allowed through if mapped (or in any case if allow_unmapped=True). This is intended to address a specific issue where NovaSeq contamination presented as singleton reads. Input reads are filtered for the case where prior reads are realigned.

filter assembled reads in align_and_fix

---

docker/install-conda-dependencies.sh

solving the dependency graph for a conda environment can take a while. so long, in fact, that the conda process can run for >10 minutes without writing to stderr/stdout. That means Travis CI is likely to kill the job. This adds two functions to the conda install script to start a subshell process that writes out periodically to keep the build job alive. It also enforces a hard timelimit on the conda instal job via the timeout from GNU coreutils

run keepalive subshell during conda install

---

illumina.py

Adds --max_barcodes option (default 10000) to illumina.illumina_demux to stop runaway behavior on large flowcells. On NovaSeq runs, the demux itself will often complete hours before the barcode counting finishes writing its output to disk. Interestingly, the barcode counting (in sqlite) is reasonably fast: it's the writing of the output file that is slow.

add 10k limit to common barcodes output

---

illumina.py

meta_by_sample should index on sanitized sample name, not original sample name

demux meta_by_sample output fix

---

illumina.py
test/input/TestIlluminaBarcodeHelper/single_index/expected.txt
util/illumina_indices.py

bugfix guess barcodes for single-end reads; allow barcodes other than 8bp in the sorted common barcodes output file

bugfix guess barcodes for single-end reads

---

util/illumina_indices.py

skip standardization in sample read count outlier detection if stdev==0, which can happen when all read counts happen to be the same

skip standardization in sample outlier detection if stdev==0

---

util/file.py

in tarball unpacking code, allow concatenated tarballs. Owing to tar's history as a way to create Tape ARchive backups, tar files can be joined by being concatenated together. The final block is padded with zeros though (indicating EOF), which can cause tar to terminate prematurely when concatenated tarballs are being unpacked unless it is told to tolerate these early stops. This adds the `--ignore-zeros` flag to make tarball extraction more permissive. Note: this applies only to uncompressed tarballs (including concatenated tarballs within compressed archives). Our tarball repacking code already tolerates such tarballs; background info here: https://github.com/broadinstitute/viral-ngs/pull/853#issuecomment-406634371

in tarball unpacking code, allow concatenated tarballs

---

requirements-conda.txt

add `jinja2>=2.11.3` to requirements for templating of various things, including [NCBI submission templates](https://submit.ncbi.nlm.nih.gov/genbank/template/submission/)

add jinja2>=2.11.3 to requirements

---

illumina.py

illumina_demux outputs some metadata in json files which then get read into WDL `Map[String,String]` objects via the WDL `read_json` function. Most engines are not smart enough to dynamically coerce integers to strings during this load, so we will need to keep things simple in our json outputs here and convert all numbers to strings before writing out.

convert all json map values to strings

---

illumina.py

set the `sequencer_model` runinfo json output value to a string instead of a dict

illumina_demux runinfo json output

---

reports.py

`reports.py plot_coverage`: do not `eval()` input to set plot binning function; add `mean()` and `median()` to options for binning stat

plot_coverage: do not eval() input to set plot binning function; add mean() and median() to options for binning stat

---

.github/workflows/build.yml

rename test action in CI to remove mention of py version since the action host python version is irrelevant, since the one used for testing is set in viral-core: https://github.com/broadinstitute/viral-core/blob/master/Dockerfile#L30

rename test action in CI

---

illumina.py
util/illumina_indices.py

in `illumina.py guess_barcodes`, this now counts NTCs by prefix if their count is not specified, defaulting to count samples starting with "neg", "water", "NTC", or "H2O" as negative controls. The user can specify their own prefix for negative controls via the newly-added "--neg_control_prefixes" argument, which is mutually-exclusive with "--number_of_negative_controls". If neither is specified, NTCs are counted based on prefix.

in illumina.py guess_barcodes, count NTCs by prefix if their count is not specified

---

read_utils.py

add read_utils.py::filter_bam_to_proper_primary_mapped_reads() to remove from a bam file any reads not flagged as being properly paired. This same functionality is added as an optional feature of minimap2_idxstats and bwamem_idxstats if --filterReadsAfterAlignment is specified (preserving the prior functionality for invocations calling these functions the old way, without --filterReadsAfterAlignment)

add read_utils.py::filter_bam_to_proper_primary_mapped_reads(); add same and expose in minimap2_idxstats and bwamem_idxstats

---

read_utils.py
tools/samtools.py

add a parameter to remove the read duplicate flag bit from the read exclusion criteria in filter_bam_to_proper_primary_mapped_reads; CLI commands making use of this function now now accept an optional --keepDuplicates flag

add parameter to remove duplicate bit as exclusion criterion in filter_bam_to_proper_primary_mapped_reads

---

.coveragerc
.github/workflows/build.yml
.gitignore
conftest.py
requirements-conda-tests.txt

update coverage config (.coveragerc) and testing config (conftest.py) inherited by derived docker images, set coveralls to use relative paths (since absolute paths reported by coveralls from tests within the docker container do not match those on the GitHub runner). This also sets the number of test runners to nproc rather than a hard-coded value

update coverage config and testing config inherited by derived docker images

---

illumina.py
read_utils.py
requirements-conda.txt
util/cmd.py

In cmd.py argparse common_args(), set default number of threads to all available if `--threads` is unspecified; previously if the threads arg were None, it would be up to the consuming function to set the thread count to all available. With this change, the new default is to use all available cores. Additionally, this sanitizes the user-requested thread count via util.misc.sanitize_thread_count(), if a value is specified. This was already the behavior in most multi-threaded functions, by separate calls to util.misc.sanitize_thread_count() where a threads arg is consumed; the latter could potentially be refactored out if we are relying solely on the argparse interface, though it should be preserved for python import usage of the same functions (including some test cases). Changing the …

In cmd.py argparse common_args(), set default number of threads to all available if --threads is unspecified

---

Dockerfile
requirements-conda.txt

update viral-baseimage 0.2.2 -> [0.2.3](https://github.com/broadinstitute/viral-baseimage/releases/tag/0.2.3) (containing fully-featured qsv)

update viral-baseimage 0.2.2 -> 0.2.3 (with fully-featured qsv)

---

.readthedocs.yml
docs/conf.py

Our readthedocs configuration has fallen behind their required syntax -- update these. (build confirmed [here](https://readthedocs.org/projects/viral-core/builds/) with rendering [here](https://viral-core.readthedocs.io/en/docs/))

more ReadTheDocs fixes

---

util/version.py

When derived modules (i.e. [viral-classify](https://github.com/broadinstitute/viral-classify)) are symlinked into `viral-core` and their versions are read from a `VERSION` file, only the path to the viral-core version file was read. 
This changes that behavior, so outer members of the call stack are checked for the presence of VERSION files as well (and if found, the version is read from the first/outermost one found).
(i.e. when calling `./taxon-filter.py --version`, with these changes, the version of `viral-classify` is correctly returned rather than the version of `viral-core`)
Since this relies on the presence of a `VERSION` file to find the current "project path", this will fall back to the old behavior if `viral-core` has a `VERSION` file but the derived module lacks such a file. …

in util.version.py::get_project_path(), consider calling modules to report VERSION correctly

---

read_utils.py

This PR makes read_utils.align_and_fix tolerate whitespace and other unusual characters in the fasta sequence headers by sanitizing the headers prior to indexing and alignment.

align_and_fix: tolerate whitespace in headers

---

requirements-conda.txt

add the [NCBI datasets](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-install/) CLI tools to conda dependencies, for downloading viral genomes and associated metadata

add NCBI datasets to conda dependencies

---

docker/calc_mem.py
requirements-conda.txt
test/unit/test_util_misc.py
util/misc.py

update calc_mem.py script used to obtain within-container memory limit for cgroup v2, obtaining memory limit from new read-only file, falling back to psutil-based approach. Additionally, allow calc_mem.py to return memory values in kb or b. Also update CPU limit for cgroup v2 in calc_mem.py and util.misc; add psutil to conda requirements

update calc_mem.py script used to obtain within-container memory limit for cgroup v2
